/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=AssemblyBindings worker/bindings.d.ts` (hash: 0a404a9d58df36bfd9706b36d7af634d)
interface __BaseEnv_AssemblyBindings {
	DB: D1Database;
	API_LIMITER: RateLimit;
	REGISTER_LIMITER: RateLimit;
	WRITE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	DEPLOYMENT_ENV: string;
	ALLOWED_ORIGINS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface StagingEnv {
		DB: D1Database;
		API_LIMITER: RateLimit;
		REGISTER_LIMITER: RateLimit;
		WRITE_LIMITER: RateLimit;
		ASSETS: Fetcher;
		DEPLOYMENT_ENV: string;
		ALLOWED_ORIGINS: string;
	}
	interface Env extends __BaseEnv_AssemblyBindings {}
}
interface AssemblyBindings extends __BaseEnv_AssemblyBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEPLOYMENT_ENV" | "ALLOWED_ORIGINS">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}
